### ISSUE TITLE
Lego Worlds not launching in BPM anymore since latest update of Steam client

### ISSUE THREAD

**Issue by andreashuetter** [ValveSoftware/steamos-compositor#10]
Since the latest update of the Steam client only two days ago ago, Lego Worlds when using Proton on Linux won't launch from Big Picture Mode (BPM) anymore. Tried different versions of Proton, but no luck.
When launching the game in "normal" mode (non-BPM) then everything is fine.

I did some additional testing on multiple machines, though. Seems that BPM for this game is only broken on systems that are using the SteamOS Compositor (i.e. SteamOS, GamerOS, ChimeraOS) but NOT on systems that are using their own Compositor (e.g. Manjaro, ...).
So for example on Manjaro it works in both modes ("normal mode" and Big Picture Mode) whereas in SteamOS it only works when I force it to close BPM and to use the Gnome Compositor instead of the SteamOS Compositor.
So the problem seems to be related to the SteamOS Compositor. But as far as I am aware there has been no update to the SteamOS Compositor recently. So it seems that something in the latest update of the Steam Client broke something in regards of the coaction between the Steam Client and the SteamOS Compositor.

**Comment by alkazar** [comment]
Yes, this appears to be a bug in the Steam client. This affects much more than just LEGO Worlds. Many, if not almost all games are affected.

The latest version of steamos-compositor-plus (the fork of steamos-compositor used by ChimeraOS) includes a work around for this issue.

See here for details: https://github.com/ValveSoftware/steam-for-linux/issues/7966

**Comment by kisak-valve** [comment]
Closing in favor of the older issue report.
