### ISSUE TITLE
How do I intergrate/submit my own upscaler to be apart of gamescope?

### ISSUE THREAD

**Issue by KingOwnageXV** [ValveSoftware/steamos-compositor#11]
Hello, I was wondering if their is an official process to get your own upscaler intergrated into gamescope - I am a co-creator of the program "Lossless Scaling" which you can find here: https://store.steampowered.com/app/993090

We have been working on our own lightweight spatial upscaler to compete with FSR 1 and in many ways it exceeds it in quality to some degree. It's called "LS1" and I am willing to share the source code with gamescope if they are willing to at least look at it for potential integration. It works great on APUs and provides excellent upscaling quality and theirs even a more light performance version of it too.

If I'm not in the right place to request this please direct me where or give me some contact information, as this is currently the best spatial upscaler to date. I am also willing to provide a free license key of the software with any gamescope dev if they are interested, thank you for your time

**Comment by kisak-valve** [comment]
Hello @KingOwnageXV, gamescope at this point is unrelated to steamos-compositor. You can find its upstream repository at https://github.com/Plagman/gamescope.
