### ISSUE TITLE
Desktop crashes when fullscreen gamescope gets minimized while switching workspaces

### ISSUE THREAD

**Issue by AlexanderWKoenig** [ValveSoftware/steamos-compositor#9]
Hi,

i've tested the forked gamescope, it works quite well, tanks for that. :+1: 
But when i toggle fullscreen with super+f and switch my workspace, the gamescope window gets minimized. It can happen that my whole desktop crashes and just shows a blackscreen with a white cursor. But its not consistent, sometimes it works, but most of the time I get the black screen.

I've running a xfce4 session and **compiz** with up to date mesa drivers.
This could just be an issue with compiz and its window animations, but i've nether expirienced this behaviour with anyother programm/game.

**As a workaround** i've added gamescope to "non minimizeable windows" in CompizConfigSettingManager in the "Windows rules"-Plugin. No crashes anymore when switching workspaces, since the window will then just gets in window mode and wont get minimized.

**Comment by kisak-valve** [comment]
Hello @AlexanderWKoenig, looks like you intended to give feedback for https://github.com/Plagman/gamescope instead of this project. Please use gamescope's issue tracker for feedback meant for the newer project.

**Comment by AlexanderWKoenig** [comment]
> Hello @AlexanderWKoenig, looks like you intended to give feedback for https://github.com/Plagman/gamescope instead of this project. Please use gamescope's issue tracker for feedback meant for the newer project.

I did, they said i should report it upstream. Isnt this here?
Should I reopen this issue?
https://github.com/Plagman/gamescope/issues/92

**Comment by kisak-valve** [comment]
Looking at that issue report, I read "upstream" as the Desktop Environment, since that's what is crashing. @emersion, is that correct?

**Comment by AlexanderWKoenig** [comment]
Yes you are right

**Comment by emersion** [comment]
Yes. The DE you're using shouldn't crash no matter what.
